name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 14 * * *'  # Runs at 14:30 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "saitharun.p@gramener.com"
          
      - name: Create daily commit
        run: |
          date >> last_update.txt
          git add last_update.txt
          git commit -m "Daily automated commit $(date)"
          git push
