name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "saitharun.p@gramener.com"

      - name: Make a commit
        run: |
          echo "Daily commit $(date)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Automated commit - $(date)"
          git push
