name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 5:30 AM UTC (change as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "saitharun.p@gramener.com"

      - name: Make Changes
        run: |
          echo "$(date)" >> daily-log.txt  # Append timestamp to a file

      - name: Commit and Push Changes
        run: |
          git add daily-log.txt
          git commit -m "Daily commit - $(date)"
          git push
